/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View_MVC;

/**
 *
 * @author xpimenta
 */
public class TelaBanhoTosa extends javax.swing.JFrame {

    /**
     * Creates new form TelaBanhoTosa
     */
    public TelaBanhoTosa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JPanel_Tela_BanhoeTosa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JPanel_Tela_BanhoeTosa_VerificarDados = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jLabel16 = new javax.swing.JLabel();
        JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificar = new javax.swing.JButton();
        JPanel_Tela_BanhoeTosa_Info = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JPanel_Tela_BanhoeTosa_ConfirmarES = new javax.swing.JPanel();
        JButton_TelaBanhoeTosa_ConfirmarEntrada = new javax.swing.JButton();
        JButton_TelaBanhoeTosa_ConfirmarSaida = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel_Tela_BanhoeTosa.setBackground(new java.awt.Color(204, 255, 255));
        JPanel_Tela_BanhoeTosa.setForeground(new java.awt.Color(102, 102, 102));
        JPanel_Tela_BanhoeTosa.setToolTipText("");

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 36)); // NOI18N
        jLabel1.setText("Banho | Tosa");

        JPanel_Tela_BanhoeTosa_VerificarDados.setBackground(new java.awt.Color(245, 245, 245));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 153));
        jLabel17.setText("CPF Dono");

        jScrollPane1.setViewportView(jTextPane1);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 153));
        jLabel18.setText("Apelido Animal");

        jScrollPane2.setViewportView(jTextPane2);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Verificar dados");

        JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificar.setIcon(new javax.swing.ImageIcon("A:\\Bibliotecas\\Documentos\\POO2\\trabbb\\trabalhoPOO2\\View_MVC\\Icons\\icons8-pesquisar-64.png")); // NOI18N
        JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_Tela_BanhoeTosa_VerificarDadosLayout = new javax.swing.GroupLayout(JPanel_Tela_BanhoeTosa_VerificarDados);
        JPanel_Tela_BanhoeTosa_VerificarDados.setLayout(JPanel_Tela_BanhoeTosa_VerificarDadosLayout);
        JPanel_Tela_BanhoeTosa_VerificarDadosLayout.setHorizontalGroup(
            JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createSequentialGroup()
                .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createSequentialGroup()
                                .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel18)))
                                .addGap(38, 38, 38)
                                .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanel_Tela_BanhoeTosa_VerificarDadosLayout.setVerticalGroup(
            JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(JPanel_Tela_BanhoeTosa_VerificarDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(29, 29, 29)
                .addComponent(JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificar)
                .addGap(71, 71, 71))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel4.setText("Animal");

        javax.swing.GroupLayout JPanel_Tela_BanhoeTosa_InfoLayout = new javax.swing.GroupLayout(JPanel_Tela_BanhoeTosa_Info);
        JPanel_Tela_BanhoeTosa_Info.setLayout(JPanel_Tela_BanhoeTosa_InfoLayout);
        JPanel_Tela_BanhoeTosa_InfoLayout.setHorizontalGroup(
            JPanel_Tela_BanhoeTosa_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_Tela_BanhoeTosa_InfoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45))
            .addGroup(JPanel_Tela_BanhoeTosa_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanel_Tela_BanhoeTosa_InfoLayout.setVerticalGroup(
            JPanel_Tela_BanhoeTosa_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_Tela_BanhoeTosa_InfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanel_Tela_BanhoeTosa_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
        );

        JButton_TelaBanhoeTosa_ConfirmarEntrada.setText("Confirmar entrada");
        JButton_TelaBanhoeTosa_ConfirmarEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_TelaBanhoeTosa_ConfirmarEntradaActionPerformed(evt);
            }
        });

        JButton_TelaBanhoeTosa_ConfirmarSaida.setText("Confirmar Saida");
        JButton_TelaBanhoeTosa_ConfirmarSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_TelaBanhoeTosa_ConfirmarSaidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_Tela_BanhoeTosa_ConfirmarESLayout = new javax.swing.GroupLayout(JPanel_Tela_BanhoeTosa_ConfirmarES);
        JPanel_Tela_BanhoeTosa_ConfirmarES.setLayout(JPanel_Tela_BanhoeTosa_ConfirmarESLayout);
        JPanel_Tela_BanhoeTosa_ConfirmarESLayout.setHorizontalGroup(
            JPanel_Tela_BanhoeTosa_ConfirmarESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_Tela_BanhoeTosa_ConfirmarESLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(JButton_TelaBanhoeTosa_ConfirmarEntrada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JButton_TelaBanhoeTosa_ConfirmarSaida)
                .addGap(38, 38, 38))
        );
        JPanel_Tela_BanhoeTosa_ConfirmarESLayout.setVerticalGroup(
            JPanel_Tela_BanhoeTosa_ConfirmarESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_Tela_BanhoeTosa_ConfirmarESLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanel_Tela_BanhoeTosa_ConfirmarESLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JButton_TelaBanhoeTosa_ConfirmarEntrada)
                    .addComponent(JButton_TelaBanhoeTosa_ConfirmarSaida))
                .addContainerGap())
        );

        javax.swing.GroupLayout JPanel_Tela_BanhoeTosaLayout = new javax.swing.GroupLayout(JPanel_Tela_BanhoeTosa);
        JPanel_Tela_BanhoeTosa.setLayout(JPanel_Tela_BanhoeTosaLayout);
        JPanel_Tela_BanhoeTosaLayout.setHorizontalGroup(
            JPanel_Tela_BanhoeTosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_Tela_BanhoeTosaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel_Tela_BanhoeTosa_VerificarDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanel_Tela_BanhoeTosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_Tela_BanhoeTosaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(JPanel_Tela_BanhoeTosa_ConfirmarES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JPanel_Tela_BanhoeTosa_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        JPanel_Tela_BanhoeTosaLayout.setVerticalGroup(
            JPanel_Tela_BanhoeTosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_Tela_BanhoeTosaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(JPanel_Tela_BanhoeTosaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanel_Tela_BanhoeTosa_Info, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanel_Tela_BanhoeTosaLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(JPanel_Tela_BanhoeTosa_VerificarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JPanel_Tela_BanhoeTosa_ConfirmarES, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_Tela_BanhoeTosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPanel_Tela_BanhoeTosa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButton_TelaBanhoeTosa_ConfirmarEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_TelaBanhoeTosa_ConfirmarEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_TelaBanhoeTosa_ConfirmarEntradaActionPerformed

    private void JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificarActionPerformed

    private void JButton_TelaBanhoeTosa_ConfirmarSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_TelaBanhoeTosa_ConfirmarSaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JButton_TelaBanhoeTosa_ConfirmarSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaBanhoTosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaBanhoTosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaBanhoTosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaBanhoTosa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaBanhoTosa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_TelaBanhoeTosa_ConfirmarEntrada;
    private javax.swing.JButton JButton_TelaBanhoeTosa_ConfirmarSaida;
    private javax.swing.JButton JButton_Tela_BanhoeTosa_VerificarDados_ActionVerificar;
    private javax.swing.JPanel JPanel_Tela_BanhoeTosa;
    private javax.swing.JPanel JPanel_Tela_BanhoeTosa_ConfirmarES;
    private javax.swing.JPanel JPanel_Tela_BanhoeTosa_Info;
    private javax.swing.JPanel JPanel_Tela_BanhoeTosa_VerificarDados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables
}
